#!/bin/sh

export TERM="xterm"
export PATH="<?php echo env('PATH'); ?>"

cd <?php echo APP; ?>

if [ -n "$1" ]; then
	cake post_receive commit <?php echo $project; ?>

else
	while read oldrev newrev refname
		do
		cake post_receive commit <?php echo $project; ?> $refname $oldrev $newrev
	done
fi
