#!/bin/sh

export TERM="xterm"
export PATH="<?php echo env('PATH'); ?>:<?php echo @$root; ?>"

cd <?php echo APP; ?>


if [ -n "$1" ]; then
	chaw pre_receive <?php echo @$project; ?><?php echo (!empty($fork)) ? " -fork {$fork}" : null; ?>

else
	while read oldrev newrev refname
		do
		chaw pre_receive <?php echo @$project; ?><?php echo (!empty($fork)) ? " -fork {$fork}" : null; ?> $refname $oldrev $newrev
	done
fi
