#!/bin/sh
refname="$1"
oldrev="$2"
newrev="$3"

export TERM="xterm"
export PATH="<?php echo env('PATH'); ?>:<?php echo $chaw; ?>"

cd <?php echo APP; ?>

cake update <?php echo $project; ?> $refname $oldrev $newrev

exit $?